### PR TITLE
Add build support for Visual Studio/MSVC

### PR DESCRIPTION
**Pull request by lithiumfluorine**
Since Visual Studio does support std::filesystem, I just needed to clean up the CMakeLists and fix some small problems that occured when compiling. 

I also did some cleaning in README to reflect build support.

I have not tested if this breaks MinGW compilation, due to not having it installed. It *shouldn't*, but I don't know. Please do test that before merging. 🙂

### CODE REVIEW

**Comment by alcros33** [comment]
Hi,
CmakeLists.txt has a problem:
target_link_libraries is called twice for the target MemoryHandler.dll.
First on line 111 and then on line 120.
An easy fix for this is Replacing those lines with the following:

```cmake
add_library(${MAIN_LIBRARY_NAME} SHARED ${SOURCES} )
if (MSVC)
    target_link_libraries(${MAIN_LIBRARY_NAME} PSAPI)
    target_compile_options(
        ${MAIN_LIBRARY_NAME} PUBLIC 
        "/std:c++17" 
        "/permissive-"
    )
else()
    target_link_libraries(${MAIN_LIBRARY_NAME} PSAPI stdc++fs)
endif()
```
Also please do not remove the "stdc++fs" from the target_link_libraries at line 127, it is necesary for MINGW compilation... If it breaks VS add an if else:
```cmake
if(MSVC)
    target_link_libraries(${PROJECT_NAME} ${MAIN_LIBRARY_NAME} Qt5::Widgets)
else()
    target_link_libraries(${PROJECT_NAME} stdc++fs ${MAIN_LIBRARY_NAME} Qt5::Widgets)
endif()
```
 With these changes it does compile fine now

**Comment by alcros33** [comment]
Also on line 65 theres a " IF (NOT MSVC) " and a few lines below theres a "IF (MINGW)" please remove one out of these two.

Same as the "IF (WIN32)" they were previously "IF (MINGW)" because I used a template which was intended to be compatible with linux and windows but since MHW is only available on windows, then they are no longer necesary.

And finally... what is the definition "NOMINMAX" for?

**Comment by lithiumfluorine** [comment]
This should fix those problems, please try it again :)

> target_link_libraries is called twice for the target MemoryHandler.dll.

I honestly didn't know that wasn't allowed. 😮 

> but since MHW is only available on windows, then they are no longer necesary.

Oh right. Didn't even consider that while rewriting it. 

>And finally... what is the definition "NOMINMAX" for?

Since `windows.h` is really, really old it by default defines some macros called `max()` and `min()`, which causes a bunch of issues with the C++ STL. More specifically, I got compile errors on line 32 of `PlayerData.hpp`. Defining `NOMINMAX` causes `windows.h` to do the sensible thing and not define those macros. Maybe MinGW uses a custom `windows.h` that does the reasonable thing by default?

**Comment by alcros33** [comment]
Hi there,
I think you forgot to add the linking of PROJECT_NAME to stdc++fs on line 129. Also please link to it before linking to MAIN_LIBRARY.... Yes, I know that it sounds stupid because MAIN_LIBRARY is already linked to stdc++fs...  But I don't know why that is the only way that worked for me...
Please replace line 129 with something like this:
```cmake
if(MSVC)
    target_link_libraries(${PROJECT_NAME} ${MAIN_LIBRARY_NAME} Qt5::Widgets)
else()
    target_link_libraries(${PROJECT_NAME} stdc++fs ${MAIN_LIBRARY_NAME} Qt5::Widgets)
endif()
```
(The change below is a suggestion, not necesary)
Also ... I don't really like that "#define NOMINMAX" on the Process.hpp file, could you add the definition as a flag command? something like this below...
```cmake
IF (MSVC)
    # You can do things like this on the Microsoft compiler right?
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DNOMINMAX")
ENDIF()
```

**Comment by lithiumfluorine** [comment]
Hopefully fixed it now.

It is kinda weird that stdc++fs doesn't get linked into the executable since it *should* get linked as a transitive dependecy of the library, but since that doesn't work...  We just have to do it like you said :)

**Pull request merged**
